### ISSUE TITLE
Outright confusing example of test cases

### ISSUE THREAD

**Issue by installubun2** [ashleygwilliams/a-very-brief-intro-to-rust#10]
In the example test function, it demonstrates your complete lack of understanding for how Option<_> works in Rust. You supply the argument some of the time, in the form of what should be the "contained" type, and in another test, you leave it out altogether. Not to mention that the input type for the tested function does not take an Option<_>.

**Comment by ashleygwilliams** [comment]
hi! PRs are welcome. please note that if you are rude in the issues you file i (and honestly any maintainer) is less likely to be welcoming to your feedback.

this is something that i made on a weekend and published for fun. there are mistakes in it. that's OK. it does not demonstrate my complete lack of understanding. does it show that i didn't fully review and edit my work? yes. 

if you continue to aggressively file issues, rudely, with no PRs, i will ban you from the repo. please consider changing your tone.

**Comment by installubun2** [comment]
@ashleygwilliams hey, I will submit PRs when I get the opportunity :)
